services:
  db:
    image: postgres:16
    container_name: recommendation_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: recommendationdb
    ports:
      - "5440:5432"
    networks:
      - my_shared_network

  redis:
    image: redis:latest
    container_name: recommendation_redis
    ports:
      - "6379:6379"
    networks:
      - my_shared_network

  app:
    image: recservice:latest
    container_name: recservice
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
      - ./migrations:/app/migrations
    environment:
      CONFIG_PATH: /app/.env
      KAFKA_BROKER: kafka:9092
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "8084:8084"
    command: ["/bin/sh", "-c", "/usr/local/bin/wait-for-it db:5432 -- sleep 5 && ./recservice"]
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: true