// Code generated by mockery v2.51.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Kafka is an autogenerated mock type for the Kafka type
type Kafka struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *Kafka) Close() {
	_m.Called()
}

// SendMessage provides a mock function with given fields: key, value
func (_m *Kafka) SendMessage(key string, value interface{}) error {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewKafka creates a new instance of Kafka. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKafka(t interface {
	mock.TestingT
	Cleanup(func())
}) *Kafka {
	mock := &Kafka{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
