services:
  db:
    image: postgres:16
    container_name: user_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: userdb
    ports:
      - "5438:5432"
    networks:
      - my_shared_network

  app:
    image: userservice:latest
    container_name: userservice
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
      - ./migrations:/app/migrations
    environment:
      CONFIG_PATH: /app/.env
      KAFKA_BROKER: kafka:9092
    ports:
      - "8082:8082"
    command: ["/bin/sh", "-c", "/usr/local/bin/wait-for-it db:5432 -- sleep 15 && ./userservice"]
    networks:
      - my_shared_network

networks:
  my_shared_network:
    external: true